--Tạo Database QLBH--
CREATE DATABASE QLBH

--Tạo bảng và khóa chính--
CREATE TABLE KHACHHANG
(
	MAKH char(4) NOT NULL,
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	NGDK smalldatetime,
	DOANHSO money,
	CONSTRAINT PK_KH PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN
(
	MANV char(4) NOT NULL,
	HOTEN varchar(40),
	SODT varchar(20),
	NGVL smalldatetime,
	CONSTRAINT PK_NV PRIMARY KEY(MANV)
)

CREATE TABLE SANPHAM
(
	MASP char(4) NOT NULL,
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(40),
	GIA money,
	CONSTRAINT PK_SP PRIMARY KEY(MASP)
)

CREATE TABLE HOADON
(
	SOHD int NOT NULL,
	NGHD smalldatetime,
	MAKH char(4),
	MANV char(4),
	TRIGIA	money,
	CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)

CREATE TABLE CTHD
(
	SOHD int NOT NULL,
	MASP char(4) NOT NULL,
	SL int,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP)
)

--Tạo khóa ngoại--
ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)

--Câu 2--
ALTER TABLE SANPHAM ADD GHICHU varchar(20)

--Câu 3--
ALTER TABLE KHACHHANG ADD LOAIKH tinyint

--Câu 4--
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100)

--Câu 5--
ALTER TABLE SANPHAM
DROP COLUMN GHICHU

--Câu 6--
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH varchar(30)

--Câu 7--
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_DVT CHECK ((DVT='cay') or (DVT = 'hop') or (DVT = 'cai') or (DVT = 'quyen') or (DVT = 'chuc'))

--Câu 8--
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_GIA CHECK (GIA >= 500)

--Câu 9--
ALTER TABLE CTHD
ADD CONSTRAINT CHK_SL CHECK (SL>=1)

--Câu 10--
ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGDK CHECK (NGDK > NGSINH)