--Tao database QLGV--
CREATE DATABASE QLGV

--Tao Table va khoa chinh--
CREATE TABLE KHOA
(
	MAKHOA varchar(4) NOT NULL,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)

CREATE TABLE MONHOC
(
	MAMH varchar(10) NOT NULL,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4),
	CONSTRAINT PK_MH PRIMARY KEY(MAMH)
)

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10) NOT NULL,
	MAMH_TRUOC varchar(10) NOT NULL,
	CONSTRAINT PK_DK PRIMARY KEY(MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN
(
	MAGV char(4) NOT NULL,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),
	CONSTRAINT PK_GV PRIMARY KEY(MAGV)
)

CREATE TABLE LOP
(
	MALOP char(3) NOT NULL,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)

CREATE TABLE HOCVIEN
(
	MAHV char(5) NOT NULL,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3),
	CONSTRAINT PK_HV PRIMARY KEY(MAHV)
)

CREATE TABLE GIANGDAY
(
	MALOP char(3) NOT NULL,
	MAMH varchar(10) NOT NULL,
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	CONSTRAINT PK_GD PRIMARY KEY(MALOP, MAMH)
)

CREATE TABLE KETQUATHI
(
	MAHV char(5) NOT NULL,
	MAMH varchar(10) NOT NULL,
	LANTHI tinyint NOT NULL,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10),
	CONSTRAINT PK_KQT PRIMARY KEY(MAHV, MAMH, LANTHI)
)

--Thiet lap khoa ngoai--

--makhoa---
ALTER TABLE MONHOC ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

--malop--
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

--mamonhoc--
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
CONSTRAINT FK_DK_MHT FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KQT_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

--magv--
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_GV FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GV FOREIGN KEY(TRGKHOA) REFERENCES GIAOVIEN(MAGV)

--mahv--
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KQT_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_HV FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV)

--them thuoc tinh cho HOCVIEN--
ALTER TABLE HOCVIEN
ADD GHICHU varchar(20), DIEMTB numeric(4,2), XEPLOAI varchar(10)

--cau 3--
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GT CHECK ((GIOITINH='Nam') or (GIOITINH='Nu'))

--cau 4--
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM CHECK ((DIEM>=0) and (DIEM<=10))

--cau 5--
ALTER TABLE KETQUATHI ADD CONSTRAINT CHK_KQ CHECK ((KQUA = 'Dat' AND Diem >=5) OR (KQUA = 'Khong Dat' AND Diem <5))

--cau 6--
ALTER TABLE KETQUATHI ADD CONSTRAINT CHK_LT CHECK(LANTHI<=3)

--cau 7--
ALTER TABLE GIANGDAY ADD CONSTRAINT CHK_HK CHECK (HOCKY IN (1,2,3))

--cau 8--
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHK_HV CHECK (HOCVI IN ('CN', 'KS', 'ThS', 'TS', 'PTS'))
